# Generated by Django 2.2.14 on 2020-07-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200720_2115'),
        ('blog', '0007_auto_20200720_1736'),
    ]

    operations = [
    ]
